### ISSUE TITLE
Django 1.9 Exception: no `_choices` attribute

### ISSUE THREAD

**Issue by jaddison** [mfogel/django-timezone-field#25]
I realize Django 1.9 isn't out yet, but I'm seeing this error/traceback:

```
Traceback (most recent call last):
  File "./manage.py", line 25, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 331, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/.virtualenvs/proj/src/django/django/core/management/__init__.py", line 305, in execute
    django.setup()
  File "/home/vagrant/.virtualenvs/proj/src/django/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/vagrant/.virtualenvs/proj/src/django/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2231, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2214, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2203, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1448, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/vagrant/users/models/__init__.py", line 1, in <module>
    from .auth import *
  File "/vagrant/users/models/auth.py", line 27, in <module>
    class User(PermissionsMixin, TimeStampedModelMixin, DrupalNodeModelMixin, AbstractBaseUser):
  File "/vagrant/users/models/auth.py", line 71, in User
    timezone = TimeZoneField(default=pytz.UTC)
  File "/home/vagrant/.virtualenvs/proj/lib/python3.4/site-packages/timezone_field/fields.py", line 53, in __init__
    if self._choices:
AttributeError: 'TimeZoneField' object has no attribute '_choices'
```

This may be related to #24 perhaps, as I am seeing the same deprecation warning too.

**Comment by mfogel** [comment]
Thanks for the early bug, when 1.9 alpha is released let's see if this is still happening. Looks like that currently scheduled for end of September.

**Comment by tarkatronic** [comment]
The error is still occurring with the alpha release. I've managed to track it down to this change: https://github.com/django/django/commit/80e3444eca045799cc40e50c92609e852a299d38

Is there a reason to not simply use `self.choices`? Or does this break in pre-1.9?

**Comment by mfogel** [comment]
Thanks. It's probably a historical reason?

At work (where we're using this app, and it's my primary use case) we just upgraded to django 1.7. So I'm going to drop 1.6 support and work on adding 1.9 support as soon as I can. Would love to get time this weekend but I don't think that's going to happen.

**Comment by mfogel** [comment]
Fixed on develop, will be in the next release.
